import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const AMU_DEPARTMENTS = [
  "Advanced Centre for Women's Studies",
  "Agricultural Economics & Business Management",
  "Agricultural Microbiology",
  "Agricultural Sciences",
  "Agronomy",
  "Amraz-e-Jild Wa Zohrawiya",
  "Anaesthesiology",
  "Anatomy",
  "Applied Chemistry",
  "Applied Mathematics",
  "Applied Physics",
  "Arabic",
  "Architecture",
  "Bio-Chemistry (JNMC)",
  "Bio-Chemistry (Life Sciences)",
  "Biodiversity Studies and Management",
  "Biotechnology",
  "Botany",
  "Business Administration",
  "Business Administration - Malappuram",
  "Business Administration - Murshidabad",
  "Cardiothoracic Surgery",
  "Cardiology",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Commerce",
  "Community Medicine",
  "Computer Engineering",
  "Computer Science",
  "Conservative Dentistry & Endodontics",
  "Dermatology",
  "Economics",
  "Education",
  "Education - Malappuram",
  "Education - Murshidabad",
  "Electrical Engineering",
  "Electronics Engineering",
  "English",
  "Entomology",
  "Fine Arts",
  "Food Processing and Engineering",
  "Foreign Languages",
  "Forensic Medicine",
  "Geography",
  "Geology",
  "Hindi",
  "History",
  "Home Science",
  "Horticulture",
  "Ilaj Bit Tadbeer",
  "Ilmul Advia",
  "Ilmul Amraz",
  "Ilmul Atfal",
  "Industrial Chemistry",
  "Interdisciplinary Biotechnology Unit",
  "International Studies",
  "Islamic Studies",
  "Jarahat",
  "Journalism in Mass Communication",
  "K. A. Nizami Centre For Quranic Studies",
  "Kulliyat",
  "Law",
  "Law - Malappuram",
  "Law - Murshidabad",
  "Library and Information Science",
  "Linguistics",
  "Malayalam",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Microbiology",
  "Moalajat",
  "Modern Indian Languages",
  "Museology",
  "Nematology",
  "Neuro Surgery",
  "Niswan wa Qabalat",
  "Obstetrics & Gynaecology",
  "Ophthalmology",
  "Oral & Dental Pathology And Microbiology",
  "Oral & Maxillofacial Surgery",
  "Orthodontics And Dentofacial Orthopedics",
  "Orthopaedic Surgery",
  "OTO-Rhino-Laryngology (E.N.T.)",
  "Paediatric Surgery",
  "Paediatrics",
  "Paediatrics & Preventive Dentistry",
  "Pathology",
  "Periodontics & Community Dentistry",
  "Persian",
  "Petroleum Studies",
  "Pharmacology",
  "Philosophy",
  "Physical Education",
  "Physical Health & Sports Education",
  "Physics",
  "Physiology",
  "Plant Pathology",
  "Plastic Surgery",
  "Political Science",
  "Post Harvest Engineering And Technology",
  "Prosthodontics/Dental Material",
  "Psychiatry",
  "Psychology",
  "Radio-Diagnosis",
  "Radiotherapy",
  "Remote Sensing and GIS Applications",
  "Saidla",
  "Sanskrit",
  "Shia Theology",
  "Social Work",
  "Sociology",
  "South African & Brazilian Studies",
  "Statistics And Operations Research",
  "Strategic & Security Studies",
  "Sunni Theology",
  "Surgery",
  "Tahaffuzi-Wa-Samaji-Tib",
  "Tashreehul Badan",
  "Tashreeh wa Munafeul Aza",
  "T.B. & Respiratory Diseases",
  "Urdu",
  "West Asian Studies And North African Studies",
  "Wildlife Sciences",
  "Women's College",
  "Women's Studies",
  "Zoology",
].sort();
